CREATE TABLE IF NOT EXISTS diary_prompts (
    id SERIAL PRIMARY KEY,
    prompt text NOT NULL,
    enabled boolean default true
);

INSERT INTO diary_prompts(prompt) 
VALUES 
('What made you feel grateful today?'),
('Describe a small moment that brought you joy.'),
('How did you challenge yourself today, and what did you learn?'),
('Write about someone who helped you or inspired you recently.'),
('What is something you are proud of accomplishing, big or small?'),
('How did you care for your physical well-being today?'),
('Share something new you learned or discovered.'),
('What is one thing you can do tomorrow to be a little kinder to yourself?'),
('Write about a place where you feel most at peace.'),
('What thoughts or feelings have been on your mind?'),
('Describe a moment when you felt connected to someone else.'),
('What is one hope you have for the future?'),
('How did you handle a challenge or setback today?'),
('What is something you are looking forward to?'),
('Write about a goal you are working towards and why it matters to you.'),
('What is something beautiful you noticed in the world around you?'),
('How did you practice self-compassion today?'),
('Share a memory that makes you smile.'),
('What is something you would like to let go of?'),
('What advice would you give to your younger self?'),
('How did you show up for others today?'),
('What is something you appreciate about your life right now?'),
('Write about a time you felt courageous.'),
('What boundaries did you set or maintain today?'),
('What is something you are curious about?'),
('How did you connect with nature today?'),
('Write about a skill you would like to develop.'),
('What is one thing you can do to make your day better tomorrow?'),
('Describe a moment when you felt proud of yourself.'),
('What is something you can do to support someone else?'),
('What is something you value in your relationships?'),
('How did you practice mindfulness or stay present today?'),
('Write about a time you felt grateful for your body.'),
('What is one thing you can do to bring more joy into your life?'),
('Describe a moment when you felt a sense of purpose.'),
('What is something you can do to challenge your thinking?'),
('Write about a memory that shaped who you are today.'),
('What is one thing you can do to improve your sleep?'),
('How did you express your creativity today?'),
('What is something you are learning about yourself?'),
('Write about a time you felt a sense of peace or calm.'),
('What is something you can do to stay connected to your values?'),
('Describe a moment when you felt inspired.'),
('What is one thing you can do to take care of your mental health?'),
('Write about a goal you achieved and how you celebrated.'),
('What is something you can do to nurture your relationships?'),
('Describe a moment when you felt a sense of wonder.'),
('What is one thing you can do to challenge yourself in a positive way?'),
('Write about a memory that taught you an important lesson.'),
('What is something you can do to be more present in your daily life?'),
('Describe a moment when you felt a sense of gratitude for your community.'),
('What is one thing you can do to support your physical health?'),
('Write about a skill you would like to share with others.'),
('What is something you can do to bring more balance into your life?'),
('Describe a moment when you felt a sense of connection to something larger than yourself.'),
('What is one thing you can do to be more intentional with your time?'),
('Write about a memory that brings you comfort.'),
('What is something you can do to nurture your creativity?'),
('Describe a moment when you felt a sense of accomplishment.'),
('What is one thing you can do to be more present in your relationships?'),
('Write about a goal you want to set for the next month.'),
('What is something you can do to challenge your assumptions?'),
('Describe a moment when you felt a sense of joy in movement.'),
('What is one thing you can do to support your emotional well-being?'),
('Write about a memory that makes you feel hopeful.'),
('What is something you can do to be more present in your work or studies?'),
('Describe a moment when you felt a sense of connection to nature.'),
('What is one thing you can do to challenge yourself intellectually?'),
('Write about a goal you want to achieve in the next year.'),
('What is something you can do to nurture your spiritual growth?'),
('Describe a moment when you felt a sense of peace in stillness.'),
('What is one thing you can do to be more intentional with your words?'),
('Write about a memory that makes you feel grateful for your friends and family.'),
('What is something you can do to challenge your perspective?'),
('Describe a moment when you felt a sense of joy in learning.'),
('What is one thing you can do to support your physical and mental health?'),
('Write about a goal you want to set for the next week.'),
('What is something you can do to be more present in your daily routines?'),
('Describe a moment when you felt a sense of connection to your community.'),
('What is one thing you can do to challenge your beliefs?'),
('Write about a memory that brings you comfort and strength.'),
('What is something you can do to nurture your relationships with yourself and others?'),
('Describe a moment when you felt a sense of joy in helping someone else.'),
('What is one thing you can do to be more intentional with your energy?'),
('Write about a goal you want to achieve in the next month.'),
('What is something you can do to challenge your fears?'),
('Describe a moment when you felt a sense of peace in nature.'),
('What is one thing you can do to support your physical health?'),
('Write about a memory that makes you feel proud of yourself.'),
('What is something you can do to be more present in your daily life?'),
('Describe a moment when you felt a sense of connection to your values.'),
('What is one thing you can do to challenge your assumptions?'),
('Write about a goal you want to achieve in the next year.'),
('What is something you can do to nurture your spiritual growth?'),
('Describe a moment when you felt a sense of joy in learning.'),
('What is one thing you can do to challenge yourself intellectually?'),
('Write about a memory that brings you comfort and strength.'),
('What is something you can do to be more intentional with your time?'),
('Describe a moment when you felt a sense of peace in stillness.'),
('What is one thing you can do to support your emotional well-being?'),
('Write about a memory that makes you feel grateful for your friends and family.'),
('What is something you can do to challenge your perspective?'),
('Describe a moment when you felt a sense of joy in helping someone else.'),
('What is one thing you can do to be more intentional with your energy?'),
('Write about a goal you want to set for the next week.'),
('What is something you can do to challenge your fears?'),
('Describe a moment when you felt a sense of peace in nature.'),
('What is one thing you can do to support your physical health?'),
('Write about a memory that makes you feel proud of yourself.'),
('What is something you can do to be more present in your daily life?'),
('Describe a moment when you felt a sense of connection to your values.'),
('What is one thing you can do to challenge your assumptions?'),
('Write about a goal you want to achieve in the next year.'),
('What is something you can do to nurture your spiritual growth?'),
('Describe a moment when you felt a sense of joy in learning.'),
('What is one thing you can do to challenge yourself intellectually?'),
('Write about a memory that brings you comfort and strength.'),
('What is something you can do to be more intentional with your time?'),
('Describe a moment when you felt a sense of peace in stillness.'),
('What is one thing you can do to support your emotional well-being?'),
('Write about a memory that makes you feel grateful for your friends and family.'),
('What is something you can do to challenge your perspective?'),
('Describe a moment when you felt a sense of joy in helping someone else.'),
('What is one thing you can do to be more intentional with your energy?'),
('Write about a goal you want to set for the next week.'),
('What is something you can do to challenge your fears?');